dependencies {
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation group: "org.osgi", name: "osgi.core", version: "6.0.0"
	testIntegrationImplementation project(":apps:frontend-data-set:frontend-data-set-admin-api")
	testIntegrationImplementation project(":apps:object:object-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}