##
## Test Suites
##

    modified.files.includes[relevant][liferay-sample-workspace-functional-rule]=**

    liferay-sample-workspace-descriptors=\
        build.gradle,\
        gradle.properties,\
        package.json,\
        settings.gradle

    # list of samples that require triggering the client-extension-web pw tests
    modified.files.includes[relevant][liferay-sample-workspace-frontend-client-extensions-playwright-rule]=\
        ${liferay-sample-workspace-descriptors},\
        **/*custom-element*/**,\
        **/*global-css*/**,\
        **/*iframe*/**,\
        **/*sample-global-js*/**,\
        **/*js-import-maps-entry*/**,\
        **/*theme-favicon*/**,\
        **/*sample-theme-spritemap*/**,\
        **/*editor-config-contributor*/**,\
        **/*theme-css*/**

    # list of samples that require triggering the frontend-data-set-admin-web pw tests
    modified.files.includes[relevant][liferay-sample-workspace-frontend-client-extensions-fds-filter-playwright-rule]=\
        ${liferay-sample-workspace-descriptors},\
        **/*fds-filter*/**

    # list of samples that require triggering the frontend-data-set-web pw tests
    modified.files.includes[relevant][liferay-sample-workspace-frontend-client-extensions-fds-cell-renderer-playwright-rule]=\
        ${liferay-sample-workspace-descriptors},\
        **/*fds-cell-renderer*/**

    relevant.rule.names=liferay-sample-workspace-functional-rule,\
        liferay-sample-workspace-frontend-client-extensions-playwright-rule,\
        liferay-sample-workspace-frontend-client-extensions-fds-cell-renderer-playwright-rule,\
        liferay-sample-workspace-frontend-client-extensions-fds-filter-playwright-rule

    test.batch.names[relevant][liferay-sample-workspace-functional-rule]=\
        functional-tomcat90-mysql57,\
        functional-workspaces-bundle-mysql57

    test.batch.names[relevant][liferay-sample-workspace-frontend-client-extensions-playwright-rule]=\
        playwright-js-tomcat90-mysql57

    test.batch.names[relevant][liferay-sample-workspace-frontend-client-extensions-fds-filter-playwright-rule]=\
        playwright-js-tomcat90-mysql57

    test.batch.names[relevant][liferay-sample-workspace-frontend-client-extensions-fds-cell-renderer-playwright-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][liferay-sample-workspace-functional-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][liferay-sample-workspace-functional-rule]=\
        (testray.main.component.name ~ "Liferay Sample Workspace")

    test.batch.run.property.query[functional-workspaces-bundle-mysql*][relevant][liferay-sample-workspace-functional-rule]=\
        (testray.main.component.name ~ "Liferay Sample Workspace")

    playwright.projects.includes[playwright-js-tomcat90-mysql57][relevant][liferay-sample-workspace-frontend-client-extensions-playwright-rule]=\
        client-extension-web

    playwright.projects.includes[playwright-js-tomcat90-mysql57][relevant][liferay-sample-workspace-frontend-client-extensions-fds-cell-renderer-playwright-rule]=\
        frontend-data-set-web

    playwright.projects.includes[playwright-js-tomcat90-mysql57][relevant][liferay-sample-workspace-frontend-client-extensions-fds-filter-playwright-rule]=\
        frontend-data-set-admin-web

##
## Testray
##

    testray.main.component.name=Liferay Sample Workspace