/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

const DEFAULT_LABEL = {
	DATA_SET: 'Sample Data Set',
};

const REL_PREFIX = 'r_dataSetToDataSet';
const REL_POSTFIX_ERC = '_c_dataSetERC';
const REL_POSTFIX_ID = '_c_dataSetId';

const CARDS_SECTION_DATA_SET_RELATIONSHIP = {
	erc: REL_PREFIX + 'CardsSections' + REL_POSTFIX_ERC,
	id: REL_PREFIX + 'CardsSections' + REL_POSTFIX_ID,
};
const LIST_SECTION_DATA_SET_RELATIONSHIP = {
	erc: REL_PREFIX + 'ListSections' + REL_POSTFIX_ERC,
	id: REL_PREFIX + 'ListSections' + REL_POSTFIX_ID,
};
const TABLE_SECTION_DATA_SET_RELATIONSHIP = {
	erc: REL_PREFIX + 'TableSections' + REL_POSTFIX_ERC,
	id: REL_PREFIX + 'TableSections' + REL_POSTFIX_ID,
};

const ACTION_DATA_SET_RELATIONSHIP = {
	erc: REL_PREFIX + 'Actions' + REL_POSTFIX_ERC,
	id: REL_PREFIX + 'Actions' + REL_POSTFIX_ID,
};

const CLIENT_EXTENSION_FILTER_DATA_SET_RELATIONSHIP = {
	erc: REL_PREFIX + 'ClientExtensionFilters' + REL_POSTFIX_ERC,
	id: REL_PREFIX + 'ClientExtensionFilters' + REL_POSTFIX_ID,
};
const DATE_FILTER_DATA_SET_RELATIONSHIP = {
	erc: REL_PREFIX + 'DateFilters' + REL_POSTFIX_ERC,
	id: REL_PREFIX + 'DateFilters' + REL_POSTFIX_ID,
};
const SELECTION_FILTER_DATA_SET_RELATIONSHIP = {
	erc: REL_PREFIX + 'SelectionFilters' + REL_POSTFIX_ERC,
	id: REL_PREFIX + 'SelectionFilters' + REL_POSTFIX_ID,
};

const SORT_DATA_SET_RELATIONSHIP = {
	erc: REL_PREFIX + 'Sorts' + REL_POSTFIX_ERC,
	id: REL_PREFIX + 'Sorts' + REL_POSTFIX_ID,
};

export {
	ACTION_DATA_SET_RELATIONSHIP,
	CARDS_SECTION_DATA_SET_RELATIONSHIP,
	LIST_SECTION_DATA_SET_RELATIONSHIP,
	TABLE_SECTION_DATA_SET_RELATIONSHIP,
	CLIENT_EXTENSION_FILTER_DATA_SET_RELATIONSHIP,
	DATE_FILTER_DATA_SET_RELATIONSHIP,
	SELECTION_FILTER_DATA_SET_RELATIONSHIP,
	SORT_DATA_SET_RELATIONSHIP,
	DEFAULT_LABEL,
};
